### ISSUE TITLE
Újabb ikon - Pára

### ISSUE THREAD

**Issue by terba** [tolnai/home_assistant_idokep_scraper#1]
Köszi a repót! Nem tudom, minek kellene ezt beszámítani, én felhősnek vettem fel bár eseget az eső is:

```yaml
# 011  - Pára

        {% elif value == '/assets/forecast-icons/011.svg' %}
          cloudy
        {% elif value == '/assets/forecast-icons/311.svg' %}
          cloudy
```

**Comment by tolnai** [comment]
Eh, pára, az mégis micsoda? :) Derült időben nem lehet pára? Vagy közel van a ködöshöz?

**Comment by terba** [comment]
Nem tudom, de ez volt az ikon és a szöveg meg az, hogy "Pára". És tényleg az volt, mint egy őserdőben, és közben csöpögött az eső is.

**Comment by terba** [comment]
Van még egy: 083 és 383 hózápor (snowy)

**Comment by terba** [comment]
És ma is egy új: 062/362 havazás (snowy)

**Comment by terba** [comment]
Változékony időjárásunknak köszönhetően megint egy új: 052/352 ónos eső (snowy-rainy)

**Comment by Tamas92** [comment]
040/340 ködszitálás (rainy)

**Comment by tolnai** [comment]
Elnézést mindenkitől, sűrű/fáradt a mostani időszak. Felraknám gyorsan a kódokat, csak épp refaktor közben állnak a file-ok és nincs kedvem vacakolni branch-ekkel. De küldjetek nyugodtan PR-t . :)

**Comment by djsomi** [comment]
Újabb ikon a ködre 400 (fog)

**Comment by tolnai** [comment]
Megkésve bár, de felvettem az új ikonokat. :)

**Comment by Gollam** [comment]
Szia @tolnai! Lerántottam 000-tól 999-ig az összes svg-t, lenne értelme felvenni az összes hiányzó ikont a kódba?

**Comment by tolnai** [comment]
@Gollam Nyiss nyugodtan PR-t rá, vagy dobj be a plusz fajtákat. A nehézség ugye annyi, hogy át kell mappelni a HA-s időjárás fajtákra, ami szűkebb lista.

**Comment by Gollam** [comment]
Persze, vágom, PR-t gondoltam. Mivel ezek csak ikonok (nincs hozzájuk sehol máshol szöveges megfelelő az időképen, ugye?), így nem biztos hogy mindegyiket ki tudom találni, a kéteseket majd legfeljebb vitassuk meg. Néhány darab van amúgy, ami hiányzik.

**Comment by tolnai** [comment]
Ping? :)

**Comment by Gollam** [comment]
Sorry, ünnepek voltak aztán minden egyéb, most leültem és kimatekoztam őket :) https://github.com/tolnai/home_assistant_idokep_scraper/pull/16

Végül amúgy ahol kétes volt ott próbáltam a meglévőből választani. Tehát ahol villám is van a képen meg szél is meg hó is, ott a hóra szavaztam.

Az s végűek ugye a +szelet jelentik, de úgy láttam azokra nem windy-t írtatok be korábban se, úgyhogy most én se azt tettem.
