### ISSUE TITLE
Good morning script / névnap

### ISSUE THREAD

**Issue by bgeza** [tolnai/home_assistant_idokep_scraper#10]
Sziasztok,
a good morning script felolvasóban van egy "calendar.nevnapok" entitás. Ezt honnan lehet beszerezni/beállítani?
Köszi

**Comment by tolnai** [comment]
A google naptáramban én felvettem egy külső URL-ről névnapos naptárat. Nem tudom már régen honnan szereztem, most ezt az URL-t mondja: https://calendar.google.com/calendar/embed?src=nq3ciks7vtu5j12a9cng94ljbs%40group.calendar.google.com&ctz=Europe%2FBudapest vagy nq3ciks7vtu5j12a9cng94ljbs@group.calendar.google.com
![image](https://github.com/tolnai/home_assistant_idokep_scraper/assets/29948020/51dd28c0-bc60-4d07-8b12-54b21247baae)
Ez úgy jelenik meg, mintha magadnak csinálnál külön naptárat, vagy a párodét is behúznád, berakja minden napra az adott névnapot, és innentől már csak a nevére hivatkozok a HA-ban, mert a HA látja az összes naptáram a calendar integrációval.
