### ISSUE TITLE
Új ikon

### ISSUE THREAD

**Issue by Tamas92** [tolnai/home_assistant_idokep_scraper#11]
Épp porvihar van nálunk: https://www.idokep.hu/assets/forecast-icons/101.svg

**Comment by terba** [comment]
Elvileg ez már kezelve van windy-ként. Lásd: #8

**Comment by Tamas92** [comment]
Látom, 1 hónapja lett hozzáadva, my bad.

**Comment by tolnai** [comment]
Köszi a segítséget @terba 😄
