### ISSUE TITLE
Eső százalék 

### ISSUE THREAD

**Issue by MonsterVic** [tolnai/home_assistant_idokep_scraper#12]
Szia !

Először is köszi szépen a munkádat, szuperül működik. 

Nem issue amit nyitnék, de Feature Request -re nincs mód a github -on tudomásom szerint. 

Szóval az volna a kérdés, hogy az eső előrejelzés százalékos esélyét valahogyan nem tudnád -e beemelni ? 
És ha továbbmennénk ebből entity -t vagy valamit varázsolni ami megfogható mint adat. 
Automata öntöző rendszer használatánál volna állati előnyös, hogy ha mondjuk reggel 6 -kor van az öntözési ciklus de azt látná a HA, hogy reggel 8 -kor eső 80% akkor egészen egyszerűen automatikusan törölném a reggel 6 -os öntözést hiszen nagy az esélye, hogy esni fog. 

Köszi bármilyen választ :)

**Comment by tolnai** [comment]
Szia, ha a weboldalon kint van, akkor +1 selectorral behúzható az is. Annyi, hogy ha jól emlékszem, az órás előrejelzésnél százalékot mutat, a napiban mm-t, szóval észnél kell lenni a mértékegységekkel felhasználásnál. Sajna most nem tudom kipróbálni, mert mostanában nem mond esőt... de nyugodtan nyiss PR-t ha neked megvan a selector. ;)

Más: Mivel nagyon sokféle adat van egy időjárás előrejelzésben, ezek ugye attribute-okban elérhetőek, nem külön entitásban, de template-ekben és autoamtion-ökben elvileg azok is felhasználhatóak. De talán jobban jársz a spéci esetedben egy származtatott értékben, ami a következő X óra százalékai alapján ad egy igen/nem-et, és aztán azzal scriptelni tovább.

**Comment by MonsterVic** [comment]
> Szia, ha a weboldalon kint van, akkor +1 selectorral behúzható az is. Annyi, hogy ha jól emlékszem, az órás előrejelzésnél százalékot mutat, a napiban mm-t, szóval észnél kell lenni a mértékegységekkel felhasználásnál. Sajna most nem tudom kipróbálni, mert mostanában nem mond esőt... de nyugodtan nyiss PR-t ha neked megvan a selector. ;)
> 
> Más: Mivel nagyon sokféle adat van egy időjárás előrejelzésben, ezek ugye attribute-okban elérhetőek, nem külön entitásban, de template-ekben és autoamtion-ökben elvileg azok is felhasználhatóak. De talán jobban jársz a spéci esetedben egy származtatott értékben, ami a következő X óra százalékai alapján ad egy igen/nem-et, és aztán azzal scriptelni tovább.

Aha, elkezdtem kicsit visszafejteni, hogy hogyan is csíped el az adatokat ezzel a multiscraper -rel azt hiszem nyomon vagyok kezdem érteni, de valóban meg kell várni amíg eső lesz mert most nem lesz így nincs ikon. :) Jelzem ha jutok valamire, meg ha nálatok hamarabb lesz eső nézz rá te is :)

**Comment by tolnai** [comment]
Ilyent lehet csinálni belőle:
![image](https://github.com/user-attachments/assets/074ad5b4-d831-4095-9b24-35c9da501d1b)

Felpusholtam egy változatot, nálam úgy tűnik működik (most épp esőt mond).

**Comment by MonsterVic** [comment]
> Ilyent lehet csinálni belőle: ![image](https://private-user-images.githubusercontent.com/29948020/361830582-074ad5b4-d831-4095-9b24-35c9da501d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODI5MjksIm5iZiI6MTcyNDc4MjYyOSwicGF0aCI6Ii8yOTk0ODAyMC8zNjE4MzA1ODItMDc0YWQ1YjQtZDgzMS00MDk1LTliMjQtMzVjOWRhNTAxZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE4MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMmViMzc0MjNhZjA1ODNlNTg1MjI1YzRlNTdjOGYyZTJiYmIwNmI3ZjFiMzZlOGE3OGU4M2ZiZTRjOWQwZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CoiNhhDdc4XL7F2G7zg5_lTXuWIZlXgDHFtcn9cvfPI)
> 
> Felpusholtam egy változatot, nálam úgy tűnik működik (most épp esőt mond).

Szuper, jól néz ki, akkor most már csak nekem is kell találni egy nekem tetsző kártyát amiben meg tudom jeleníteni :)

Köszi szépen.
