### ISSUE TITLE
csak egy kérdés

### ISSUE THREAD

**Issue by gorcsev71** [tolnai/home_assistant_idokep_scraper#14]
Az időképen ki lehet ugye választani egy lokációt, ahol az időjárásra kíváncsiak vagyunk (pl Budapest vagy Kecskemét) és úgy tűnik, hogy különböző előrejelzéseket ad Szegedre és mondjuk Cserhátszentivánra. Namármost az lenne a kérdésem, hogy az idokep scraperban lehet-e valahogy lokációt specifikálni, ha igen hogyan, ha pedig nem, akkor melyik város előrejelzését szedi le?

**Comment by tolnai** [comment]
Ööö, ha nem egyértelmű, az idokep_multiscrape.yaml file-ban a resource property-ben van az URL és benne a város...
Mint pl. `https://www.idokep.hu/idojaras/T%C3%B6r%C3%B6kb%C3%A1lint`

**Comment by gorcsev71** [comment]
Ahh, ok, köszönöm. Az encoding miatt nem ismertem fel a törökbálintot :-)
