### ISSUE TITLE
Unable to extract data from HTML

### ISSUE THREAD

**Issue by FabianGabor** [tolnai/home_assistant_idokep_scraper#3]
```
This error originated from a custom integration.

Logger: custom_components.multiscrape.entity
Source: custom_components/multiscrape/entity.py:113
Integration: Multiscrape scraping component (documentation, issues)
First occurred: 08:58:38 (45 occurrences)
Last logged: 12:28:39

Scraper_noname_0 # Időkép, napi előrejelzés adatok # day1_prec_mm # Unable to extract data from HTML
Scraper_noname_0 # Időkép, napi előrejelzés adatok # day2_prec_mm # Unable to extract data from HTML
Scraper_noname_0 # Időkép, napi előrejelzés adatok # day5_prec_mm # Unable to extract data from HTML
```

- Home Assistant 2023.9.2
- Supervisor 2023.09.2
- Operating System 10.5
- Frontend 20230911.0 - latest 
- HACS 1.32.1
- HA Multiscrape v6.7.3

**Comment by tolnai** [comment]
Az a fura, hogy emiatt van bent az `on_error` rész a csapadékos selectoroknál, és helyesen ad vissza ilyenkor 0-t, de mégis van hiba a logokban. Szóval emiatt a magam részéről nem foglalkoztam vele, mert nem tudom hogy kellene elérni hogy ne jöjjenek és gondot nem okoznak.

**Comment by tolnai** [comment]
Á, megvan, hiányzik a `log: false` ezekből a részekből. Dobok majd egy fixet rá valamikor.

**Comment by tolnai** [comment]
Küldtem egy javítást rá, nálam jónak tűnik, kérlek jelezd ha rendben van.
