### ISSUE TITLE
Havazás ikon változás

### ISSUE THREAD

**Issue by Tamas92** [tolnai/home_assistant_idokep_scraper#5]
A havazás ikonja megváltozott. Már nem a 061/361.svg, hanem 062/362.svg alatt található. 
idokep_multiscrape.yaml 97. & 99. soránál található, ha valaki esetleg megcsinálná, amíg nem jön update.

**Comment by terba** [comment]
Szerintem használatban van a 061/361 is, amikor kisebb intenzitású a havazás. A 062-t én is jeleztem a #1 alatt.

**Comment by Tamas92** [comment]
#1 - issueban jelezve, így zárom.
