### ISSUE TITLE
konfigurálás 

### ISSUE THREAD

**Issue by boyocska65** [tolnai/home_assistant_idokep_scraper#7]
Nem sikerül bekonfigurálni. Felraktam a munltiscrae-t, bemásoltam a fájljaidat, de de kezdőként olyan, mintha hiányozna a felhasználásból egy lépés.  Hol hivatkozok rá, hogy a [packages/idokep] mappában levő fájlokat elérjje a HA?

**Comment by tolnai** [comment]
Hm, most nézem, hogy a packages-re van egy hivatkozás, lehet ez kimaradt a guide-ból.
Próbáld ki kérlek ezzel a fő configuration.yaml-ban:

```
homeassistant:
  packages: !include_dir_named packages/
```

**Comment by boyocska65** [comment]
Úgy tűnik magmozdult valami. Esetleg betennéd még azt a kártyát, aminek a képe is szerepel a csomagban?

**Comment by tolnai** [comment]
Felraktam ezt is a doksiba, meg pár minta konfigot.
