### ISSUE TITLE
Na ennek találjunk megfelelőt a HA-ban

### ISSUE THREAD

**Issue by terba** [tolnai/home_assistant_idokep_scraper#8]
101 Porvihar :)

https://www.idokep.hu/assets/forecast-icons/101.svg

**Comment by terba** [comment]
401 pedig ennek az éjszakai változatának tűnik.

**Comment by tolnai** [comment]
Egyszer végig kéne nyalni 0-tól 999-ig az ikonokat... :D
windy-variant lehetne esetleg?

**Comment by terba** [comment]
Az a baj az ikonok átnézésével, hogy sokszor fogalmam nincs, hogy mit takarhat. Ha bekövetkezik az "esemény", akkor meg lehet megnézni az Időképen, hogy mi van írva az ikon fölé.

Esetleg még az ```exceptional``` lehetne. Ugye ez a múlt heti szaharai poros napon jött. Látni lehetett a port a levegőben, sárgás/barnás "köd" volt.

**Comment by tolnai** [comment]
Csak gondoltam, ha már por"vihar", akkor ugye fújja a szél a port. Az exceptional-t nem tudom igazából mire használják... hurrikán? :D Ködöt nem használnék, mert az párás. Túl részletes az időkép. :)

**Comment by terba** [comment]
Egy integráció kódját megnéztem, ott egyedül a tornádó _exceptional_. Én egy sima _windy_-re szavaznék.

**Comment by tolnai** [comment]
Azt láttad hogy a variant-ot mire használják?

**Comment by terba** [comment]
Az egyik integráció, amit megnéztem, nem használja ezt, a másik pedig valami "wind gust" (széllökés) esetén használja. A Home Assistantban a felületi szöveg ez rá:
```"windy-variant": "Windy, cloudy"```
Ezért is gondoltam, hogy inkább _windy_ legyen csak.

**Comment by tolnai** [comment]
Legyen, felvettem.
