### ISSUE TITLE
Core 2024.4.0 alatt nem megy

### ISSUE THREAD

**Issue by blacc01** [tolnai/home_assistant_idokep_scraper#9]
Szépen működött addig amíg meg nem jött a Core 2024.4.0-ás update. Előtte 2024.3.3 volt azzal ment, de az új core-al már nem megy nálam, az alábbi hibát dobja:
![image](https://github.com/tolnai/home_assistant_idokep_scraper/assets/106952013/d1d80409-759c-44f7-b26f-439c3cf214e7)

![image](https://github.com/tolnai/home_assistant_idokep_scraper/assets/106952013/776e81a0-06dd-4262-ab8d-72969a5993a0)

**Comment by tolnai** [comment]
Sajna nem szoktam .0-ás verziókra frissíteni, hátha valami még nem stabil. A legfrissebb yaml file-okat használod innen? Mert volt nemrég egy változás a template weather környékén, amikor `forecast_template` helyett bejött a `forecast_daily_template` meg `forecast_hourly_template`. A logokat is meg kellene nézni, mert ez a fenti lehet hogy csak tünet, de más okozza hogy az entity valamiért nem jött létre.

**Comment by tolnai** [comment]
Nálam 2024.4.1 alatt gond nélkül megy.
